title: Tin's Uniblog
description: > # this means to ignore newlines until "baseurl:"
  This is where I document my learnings at the Computational Arts MA at Goldsmiths College.
permalink: ':title/'
baseurl: "/uniblog" # the subpath of your site, e.g. /blog
url: "https://tingeber.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Tin's Uniblog # add your name
author-img: tinrun.jpg # add your photo
about-author: Documenting my MA in Computational Arts at Goldsmiths # add description
twitter: "@tingeber"  # add your Twitter handle
facebook: "@tingeber" # add your Facebook handle
github: tingeber # add your Github handle
keybase: tingeber # add your Linkedin handle
email: me@tin.fyi # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-98399217-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
